# Generated by Django 3.2.10 on 2022-04-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_auto_20220423_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='str_mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grh.structure'),
        ),
    ]
