"""
Django settings for grh project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import  timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
import rest_framework.permissions
from django.contrib import admin



BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@6=*y2ommaj_@eu3ffn1g9@z(-2c%ppkzr9j=6*%zquu0qs8d@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.31.50.51','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    #native django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps devloppées
    'couriers',
    'commun',
    'grh',
    # extensions
    'corsheaders',
    'rest_framework',
    'django_filters',
    'djoser',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions',
    ]
}
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://10.31.50.51:3000',
]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':timedelta(days=365),
    'AUTH_HEADER_TYPES': ('JWT','Token','Bareer'),
}
DJOSER = {
    'SERIALIZERS': {
        'user': 'grh.serializers.UserSerializer',
        'current_user': 'grh.serializers.UserSerializer',
    },
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR/'db.sqlite3',
    }
}

########## LDAP config
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType, LDAPSearchUnion

AUTH_LDAP_SERVER_URI = "ldap://AVDC1.al-mouradia.dz:389"
AUTH_LDAP_BIND_DN = 'CN=rfc,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ'
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = True
AUTH_LDAP_BIND_PASSWORD = "123456"
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "OU=LAN,DC=AL-MOURADIA,DC=DZ", ldap.SCOPE_SUBTREE, '(sAMAccountName=%(user)s)'
)

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
#
AUTH_LDAP_GROUP_SEARCH =LDAPSearch(
    "OU=ERP,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ",
    ldap.SCOPE_SUBTREE,
    "(objectClass=group)",
)


AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")
# any one should be in this groupe to be able to login
AUTH_LDAP_REQUIRE_GROUP = "CN=is_active,OU=Common,OU=ERP,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ"
# this wwill auto populate Django_user fields from ldap groups
#is_active  means the user is active or not
#is_staff  means the user can log into the django admin interface or not
# is_superuser means the user has all permissions
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "CN=is_active,OU=Common,OU=ERP,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ",
    "is_staff": "CN=is_staff,OU=Common,OU=ERP,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ",
    "is_superuser": "CN=is_superuser,OU=Common,OU=ERP,OU=Apps,OU=LAN,DC=AL-MOURADIA,DC=DZ",
}
# this will map LDAP groupes to django groupes ( not working yet !!)
AUTH_LDAP_FIND_GROUP_PERMS=True
AUTH_LDAP_MIRROR_GROUPS=True
# this will minimise too much trafic to Ldap server (will cache for 1800 sec = 30 min)
#AUTH_LDAP_CACHE_TIMEOUT = 1800

#
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django_auth_ldap": {"level": "DEBUG", "handlers": ["console"]}},
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

#####################
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'messagerie.al-mouradia.dz' # double check the settings in your outlook mailbox to make sure the host name is correct
EMAIL_PORT = 25  # double check the settings in your outlook mailbox and make sure the port number is correct
EMAIL_HOST_USER = 'h.talha'  # don't include the @blah.com part! I have made this stupid mistakes before
EMAIL_HOST_PASSWORD = 'Wxcvbn,;1993'
#################

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
