# Generated by Django 4.0.3 on 2022-03-22 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Expediteur',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
            },
        ),
        migrations.CreateModel(
            name='TypeCourier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objet', models.TextField(max_length=255)),
                ('referance_exp', models.CharField(max_length=255)),
                ('n_enregistrement', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ')], max_length=255)),
                ('date_arrivee', models.DateField()),
                ('date_expedition', models.DateField()),
                ('exige_reponse', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='couriers.classification')),
                ('destinataires', models.ManyToManyField(related_name='couriers_recus', to='couriers.entity')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_envoyes', to='couriers.entity')),
                ('reponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='couriers.courier')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='couriers.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='couriers.typecourier')),
                ('visible_a', models.ManyToManyField(related_name='couriers_visibles', to='couriers.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers.courier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
