# Generated by Django 3.2.10 on 2022-03-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_auto_20220322_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='couriers.courier'),
        ),
    ]
