# Generated by Django 3.2.10 on 2022-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_alter_attachment_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
