# Generated by Django 3.2.10 on 2022-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
