# Generated by Django 3.2.10 on 2022-04-23 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_alter_structure_str_mere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers', '0007_auto_20220423_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(editable=False, max_length=255, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grh.employe')),
                ('structure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grh.structure')),
            ],
            options={
                'verbose_name': 'Expediteur',
            },
        ),
        migrations.AlterField(
            model_name='courier',
            name='destinataires',
            field=models.ManyToManyField(related_name='couriers_recus', to='couriers.Expediteur'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_envoyes', to='couriers.expediteur'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='visible_a',
            field=models.ManyToManyField(related_name='couriers_visibles', to='couriers.Expediteur', verbose_name='Visible à'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
