# Generated by Django 3.2.10 on 2022-05-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_alter_structure_str_mere'),
        ('couriers', '0011_alter_courier_visible_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grh.structure'),
        ),
    ]
